version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "affiliate-boxy-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6dd7hfffz91t"
s3_prefix = "affiliate-boxy-serverless"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
